app:
  name: student info app
  version: app version 2.0.1

  developers:
    - Aydin
    - Ali
    - Eldar
  numbers:
    one: 1
    two: 2
    three: 3
server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/elm?createDatabaseIfNotExist=true&useSSl=true
    username: ${DB_CONNECTION_USERNAME:root}
    password: ${DB_CONNECTION_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: update

